//! Generates `RUNTIME_SEMANTICS.md` by RUNNING programs, not by reading
//! codegen.
//!
//! A type system has to explain behaviour that already exists. Writing it down
//! by hand means someone reverse-engineers 8,500 lines of codegen and gets it
//! subtly wrong; worse, the description rots the first time the runtime
//! changes. So this probes the compiler and the real WASM with a matrix of
//! small programs and records what actually happens.
//!
//! The distinction the document exists to capture is **where a mistake is
//! caught** — compile time, or at runtime as a trap. Every row marked `trap` is
//! a candidate for becoming a compile error once there are types.
//!
//! The matrix lives in `tests/common/mod.rs`, because `tests/backend_diff.rs`
//! runs the same programs through the other backend.
//!
//! `cargo test --test semantics` checks the committed document is current.
//! `P2W_BLESS=1 cargo test --test semantics` rewrites it.

mod common;
use common::{Outcome, groups, probe};

fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "# What the runtime does today\n\n\
         **Generated by `tests/semantics.rs` — do not edit by hand.** Every row \
         below was produced by compiling the program and running the real WASM \
         under wasmtime, so this describes the compiler as it is, not as anyone \
         remembers it.\n\n\
         Regenerate with `P2W_BLESS=1 cargo test --test semantics`; the test \
         fails if this file drifts.\n\n\
         ## Why this exists\n\n\
         A type system has to explain behaviour that already exists. The column \
         that matters is **where** — whether a mistake is caught by the compiler \
         or reaches the runtime as a trap:\n\n\
         | where | meaning |\n|---|---|\n\
         | `value` | compiled, ran, printed this |\n\
         | `compile error` | the compiler already refuses it |\n\
         | `trap` | it compiled, then failed at runtime with this message |\n\n\
         **Every `trap` row is a candidate to become a compile error** once \
         there are types. `tests/oracle/must-reject/` is the subset we have \
         decided should move, and `tests/oracle/README.md` says what the \
         messages then have to do.\n\n\
         Traps print their message and then execute `unreachable`. That is \
         CPython's uncaught-exception behaviour minus the traceback, which is \
         why the absence of `try`/`except` costs less than it sounds like it \
         should.\n",
    );

    for g in groups() {
        out.push_str(&format!("\n## {}\n\n{}\n\n", g.title, g.note));
        out.push_str("| program | where | result |\n|---|---|---|\n");
        for pr in &g.probes {
            let (kind, text) = match probe(pr.src) {
                Outcome::Value(v) => ("value", v),
                Outcome::CompileError(e) => ("compile error", e),
                Outcome::Trap(t) => ("trap", t),
            };
            // Keep each row on one line and safe inside a Markdown table.
            let text = text.replace('\n', " ⏎ ").replace('|', "\\|");
            let text = if text.len() > 160 {
                format!("{}…", &text[..160])
            } else {
                text
            };
            out.push_str(&format!(
                "| `{}` | {} | {} |\n",
                pr.shown.replace('|', "\\|"),
                kind,
                if text.is_empty() {
                    "(no output)".to_string()
                } else {
                    format!("`{text}`")
                }
            ));
        }
    }
    out
}

#[test]
fn runtime_semantics_document_is_current() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("RUNTIME_SEMANTICS.md");
    let generated = render();
    if std::env::var("P2W_BLESS").is_ok() {
        std::fs::write(&path, &generated).expect("write");
        eprintln!("blessed {}", path.display());
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    // Compare ignoring line endings — git normalises these on Windows.
    assert_eq!(
        committed.replace("\r\n", "\n"),
        generated,
        "RUNTIME_SEMANTICS.md is out of date. The runtime's behaviour changed \
         (or the probe list did). Review the diff — a change here is a change \
         to the language — then run: P2W_BLESS=1 cargo test --test semantics"
    );
}
