"""Regenerate src/math_wat.rs from tools/mathwat (libm -> vendored WAT).

The browser backend emits WAT with no link step, so it cannot link libm the
way every other toolchain does. This extracts the compiled functions and
lookup tables from a wasm32 build of the pinned libm crate and vendors them
as WAT text the emitter can append. Same source as the native runtime's libm
=> bit-identical transcendentals on both backends.

Usage (from the crate root):
    python tools/gen_math_wat.py

The output is committed. tests/math_wat.rs validates the vendored text and
differential-tests it against the libm crate under wasmtime, so a stale or
hand-edited artifact fails the suite rather than shipping.
"""

import io
import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CRATE = os.path.join(ROOT, "tools", "mathwat")
OUT = os.path.join(ROOT, "src", "math_wat.rs")

env = dict(os.environ)
env["RUSTC_WRAPPER"] = ""
env["CARGO_BUILD_RUSTC_WRAPPER"] = ""
# Data must land on page 0: the emitted p2w module declares one page of
# memory only when math is used. Rust's default layout puts the stack first
# at 1 MB, so shrink it — these functions spill a few words at most.
env["RUSTFLAGS"] = "-C link-arg=-zstack-size=16384 -C link-arg=--global-base=16384"

subprocess.run(
    ["cargo", "build", "--release", "--target", "wasm32-unknown-unknown"],
    cwd=CRATE, env=env, check=True,
)

meta = subprocess.run(
    ["cargo", "metadata", "--format-version", "1", "--no-deps"],
    cwd=CRATE, env=env, check=True, capture_output=True, text=True,
).stdout
target_dir = re.search(r'"target_directory":"([^"]*)"', meta).group(1)
wasm = os.path.join(target_dir, "wasm32-unknown-unknown", "release", "mathwat.wasm")

wat = subprocess.run(
    ["wasm-tools", "print", wasm], check=True, capture_output=True, text=True
).stdout

# ---- parse the numbered WAT into named, self-contained pieces -------------

export_of = {}
for m in re.finditer(r'\(export "([a-z0-9_]+)" \(func (\d+)\)\)', wat):
    export_of[int(m.group(2))] = m.group(1)
assert sorted(export_of.values()) == ["m_exp", "m_log", "m_log10", "m_log2", "m_pow"]


def fn_name(idx: int) -> str:
    # Exported functions keep their libm-facing names; internal helpers get a
    # reserved prefix that cannot collide with user symbols (those get u_) or
    # runtime helpers (p2w_ / $py_).
    return f"$mw_{export_of[idx]}" if idx in export_of else f"$mw_h{idx}"


starts = [m.start() for m in re.finditer(r"^  \(func \(;(\d+);\)", wat, re.M)]
blocks = []
for i, s in enumerate(starts):
    if i + 1 < len(starts):
        e = starts[i + 1]
    else:
        m = re.search(r"^  \((?:table|memory|global|export|data)", wat[s + 1:], re.M)
        e = s + 1 + m.start()
    blocks.append(wat[s:e].rstrip())

funcs = []
for b in blocks:
    idx = int(re.match(r"  \(func \(;(\d+);\)", b).group(1))
    b = re.sub(r"\(func \(;\d+;\) \(type \d+\)", f"(func {fn_name(idx)}", b, count=1)
    b = re.sub(r"\bcall (\d+)", lambda m: f"call {fn_name(int(m.group(1)))}", b)
    b = b.replace("global.get 0", "global.get $mw_sp").replace(
        "global.set 0", "global.set $mw_sp"
    )
    funcs.append(b)

sp_init = re.search(r"\(global \(;0;\) \(mut i32\) i32\.const (\d+)\)", wat).group(1)
data = re.search(r'^  \(data \(;0;\) \(i32\.const (\d+)\) (".*")\)$', wat, re.M)
data_off, data_bytes = data.group(1), data.group(2)

# Count real bytes (each \XX escape is one byte).
n_bytes = len(re.findall(r"\\..|[^\\\"]", data_bytes[1:-1]))

# Sanity gates — loud, never silent.
assert int(sp_init) <= 65536 and int(data_off) < 65536, "layout escaped page 0"
joined = "\n".join(funcs)
assert "(type " not in joined, "unresolved type reference survived"
assert not re.search(r"\bcall \d", joined), "numeric call survived"
assert "global.get 0" not in joined and "global.set 0" not in joined
assert 'r#"' not in joined and '"#' not in joined, "raw-string delimiter clash"

libm_ver = re.search(
    r'libm = "=(\d+\.\d+\.\d+)"',
    io.open(os.path.join(CRATE, "Cargo.toml"), encoding="utf-8").read(),
).group(1)

out = f'''//! Vendored libm transcendentals as WAT — GENERATED by tools/gen_math_wat.py,
//! do not edit. Source: tools/mathwat (libm {libm_ver}, the same pinned
//! version runtime/Cargo.toml links, so both backends carry bit-identical
//! pow/exp/log). Regenerate after bumping libm — in BOTH manifests.
//!
//! The emitter appends these only when a program actually uses them: a
//! program that never touches a fractional `**` or math.exp/log pays
//! nothing, and its module keeps having no linear memory at all.
//!
//! Entry points, all f64: $mw_m_pow(a, b), $mw_m_exp(x), $mw_m_log(x),
//! $mw_m_log2(x), $mw_m_log10(x). Everything $mw_h* is internal.

/// One 64 KiB page: lookup tables at {data_off}, shadow stack growing down
/// from {sp_init}. Emitted only alongside [`MATH_FUNCS`].
pub const MATH_MEMORY: &str = "(memory $mw_mem 1)";

/// libm's shadow stack pointer (a few words of spill space).
pub const MATH_GLOBALS: &str = "(global $mw_sp (mut i32) (i32.const {sp_init}))";

/// The polynomial/table constants: {n_bytes} bytes at offset {data_off}.
pub const MATH_DATA: &str = r#"(data (i32.const {data_off}) {data_bytes})"#;

/// {len(funcs)} functions ({len(export_of)} entry points + {len(funcs) - len(export_of)} helpers).
pub const MATH_FUNCS: &str = r#"{joined}"#;
'''
io.open(OUT, "w", encoding="utf-8", newline="\n").write(out)
print(f"wrote src/math_wat.rs: {len(funcs)} funcs, {n_bytes} data bytes at {data_off}, sp {sp_init}")
