//! Vendored libm transcendentals as WAT — GENERATED by tools/gen_math_wat.py,
//! do not edit. Source: tools/mathwat (libm 0.2.16, the same pinned
//! version runtime/Cargo.toml links, so both backends carry bit-identical
//! pow/exp/log). Regenerate after bumping libm — in BOTH manifests.
//!
//! The emitter appends these only when a program actually uses them: a
//! program that never touches a fractional `**` or math.exp/log pays
//! nothing, and its module keeps having no linear memory at all.
//!
//! Entry points, all f64: $mw_m_pow(a, b), $mw_m_exp(x), $mw_m_log(x),
//! $mw_m_log2(x), $mw_m_log10(x). Everything $mw_h* is internal.

/// One 64 KiB page: lookup tables at 16384, shadow stack growing down
/// from 16384. Emitted only alongside [`MATH_FUNCS`].
pub const MATH_MEMORY: &str = "(memory $mw_mem 1)";

/// libm's shadow stack pointer (a few words of spill space).
pub const MATH_GLOBALS: &str = "(global $mw_sp (mut i32) (i32.const 16384))";

/// The polynomial/table constants: 320 bytes at offset 16384.
pub const MATH_DATA: &str = r#"(data (i32.const 16384) "\00\00\00\00\00\00\e0?\00\00\00\00\00\00\e0\bf\00\00\00\00\00\00\f0?\00\00\00\00\00\00\f8?\00\00\00\00\00\00\00\00\06\d0\cfC\eb\fdL>\00\00\00\00\00\00\00\00\00\00\00@\03\b8\e2?Q\b4\f0\b2\96\b1D\b0\f9\ae\b6\ady\acC\ab\14\aa\eb\a8\c8\a7\aa\a6\92\a5\80\a4s\a3k\a2h\a1j\a0p\9f{\9e\8a\9d\9d\9c\b5\9b\d1\9a\f0\99\13\99:\98e\97\93\96\c4\95\f8\940\94k\93\a9\92\ea\91.\91u\90\be\8f\0a\8fY\8e\aa\8d\fe\8cT\8c\ac\8b\07\8bd\8a\c4\89%\89\89\88\ee\87V\87\c0\86+\86\99\85\08\85y\84\ec\83a\83\d8\82P\82\c9\81E\81\c2\80@\80\02\ff\0e\fd%\fbG\f9s\f7\aa\f5\ea\f34\f2\87\f0\e3\eeG\ed\b3\eb'\ea\a3\e8'\e7\b2\e5C\e4\dc\e2z\e1 \e0\cb\de}\dd4\dc\f1\da\b3\d9{\d8H\d7\1a\d6\f1\d4\cd\d3\ad\d2\92\d1{\d0i\cf[\ceQ\cdJ\ccH\cbJ\caO\c9X\c8d\c7t\c6\87\c5\9d\c4\b7\c3\d4\c2\f4\c1\16\c1<\c0e\bf\90\be\be\bd\ef\bc#\bcY\bb\91\ba\cc\b9\0a\b9J\b8\8c\b7\d0\b6\17\b6`\b5")"#;

/// 8 functions (5 entry points + 3 helpers).
pub const MATH_FUNCS: &str = r#"  (func $mw_h0 (param i32 i32 i32) (result i32)
    (local i32 i32 i64)
    i32.const 0
    local.set 3
    local.get 0
    local.set 4
    block ;; label = @1
      loop ;; label = @2
        local.get 2
        local.get 3
        i32.eq
        br_if 1 (;@1;)
        i32.const -1073741824
        local.get 0
        i64.extend_i32_u
        local.get 1
        i64.extend_i32_u
        i64.mul
        i64.const 32
        i64.shr_u
        i32.wrap_i64
        local.get 3
        i32.const 0
        i32.ne
        i32.shl
        local.tee 1
        i64.extend_i32_u
        local.get 4
        i64.extend_i32_u
        local.tee 5
        i64.mul
        i64.const 32
        i64.shr_u
        i32.wrap_i64
        i32.sub
        local.tee 0
        i64.extend_i32_u
        local.get 5
        i64.mul
        i64.const 31
        i64.shr_u
        i32.wrap_i64
        i32.const -2
        i32.and
        local.set 4
        local.get 3
        i32.const 1
        i32.add
        local.set 3
        br 0 (;@2;)
      end
    end
    local.get 4
  )
  (func $mw_h1 (param f64 i32) (result f64)
    block ;; label = @1
      block ;; label = @2
        block ;; label = @3
          block ;; label = @4
            local.get 1
            i32.const 1023
            i32.gt_s
            br_if 0 (;@4;)
            local.get 1
            i32.const -1022
            i32.ge_s
            br_if 3 (;@1;)
            local.get 0
            f64.const 0x1p-969 (;=0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002004168360008973;)
            f64.mul
            local.set 0
            local.get 1
            i32.const -1992
            i32.le_u
            br_if 1 (;@3;)
            local.get 1
            i32.const 969
            i32.add
            local.set 1
            br 3 (;@1;)
          end
          local.get 0
          f64.const 0x1p+1023 (;=89884656743115800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
          f64.mul
          local.set 0
          local.get 1
          i32.const 2046
          i32.gt_u
          br_if 1 (;@2;)
          local.get 1
          i32.const -1023
          i32.add
          local.set 1
          br 2 (;@1;)
        end
        local.get 0
        f64.const 0x1p-969 (;=0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002004168360008973;)
        f64.mul
        local.set 0
        local.get 1
        i32.const -2960
        local.get 1
        i32.const -2960
        i32.gt_u
        select
        i32.const 1938
        i32.add
        local.set 1
        br 1 (;@1;)
      end
      local.get 0
      f64.const 0x1p+1023 (;=89884656743115800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
      f64.mul
      local.set 0
      local.get 1
      i32.const 3069
      local.get 1
      i32.const 3069
      i32.lt_u
      select
      i32.const -2046
      i32.add
      local.set 1
    end
    local.get 0
    local.get 1
    i32.const 1023
    i32.add
    i64.extend_i32_u
    i64.const 52
    i64.shl
    f64.reinterpret_i64
    f64.mul
  )
  (func $mw_m_exp (param f64) (result f64)
    (local i32 i64 i32 i32 f64 f64 f64)
    global.get $mw_sp
    i32.const 16
    i32.sub
    local.tee 1
    global.set $mw_sp
    local.get 0
    i64.reinterpret_f64
    local.tee 2
    i64.const 63
    i64.shr_u
    i32.wrap_i64
    local.set 3
    block ;; label = @1
      block ;; label = @2
        block ;; label = @3
          block ;; label = @4
            block ;; label = @5
              block ;; label = @6
                block ;; label = @7
                  block ;; label = @8
                    local.get 2
                    i64.const 32
                    i64.shr_u
                    i32.wrap_i64
                    i32.const 2147483647
                    i32.and
                    local.tee 4
                    i32.const 1082532651
                    i32.lt_u
                    br_if 0 (;@8;)
                    block ;; label = @9
                      local.get 0
                      local.get 0
                      f64.eq
                      br_if 0 (;@9;)
                      local.get 0
                      local.set 5
                      br 8 (;@1;)
                    end
                    local.get 0
                    f64.const 0x1.62e42fefa39efp+9 (;=709.782712893384;)
                    f64.gt
                    br_if 2 (;@6;)
                    local.get 0
                    f64.const -0x1.6232bdd7abcd2p+9 (;=-708.3964185322641;)
                    f64.lt
                    i32.eqz
                    br_if 1 (;@7;)
                    local.get 1
                    f64.const -0x1p-149 (;=-0.000000000000000000000000000000000000000000001401298464324817;)
                    local.get 0
                    f64.div
                    f32.demote_f64
                    f32.store offset=4
                    local.get 1
                    f32.load offset=4
                    drop
                    f64.const 0x0p+0 (;=0;)
                    local.set 5
                    local.get 0
                    f64.const -0x1.74910d52d3051p+9 (;=-745.1332191019411;)
                    f64.lt
                    i32.eqz
                    br_if 1 (;@7;)
                    br 7 (;@1;)
                  end
                  block ;; label = @8
                    local.get 4
                    i32.const 1071001154
                    i32.gt_u
                    br_if 0 (;@8;)
                    local.get 4
                    i32.const 1043333120
                    i32.le_u
                    br_if 3 (;@5;)
                    f64.const 0x0p+0 (;=0;)
                    local.set 6
                    i32.const 0
                    local.set 4
                    local.get 0
                    local.set 5
                    br 6 (;@2;)
                  end
                  local.get 4
                  i32.const 1072734897
                  i32.le_u
                  br_if 3 (;@4;)
                end
                local.get 0
                f64.const 0x1.71547652b82fep+0 (;=1.4426950408889634;)
                f64.mul
                local.get 3
                i32.const 3
                i32.shl
                f64.load offset=16384
                f64.add
                i32.trunc_sat_f64_s
                local.set 4
                br 3 (;@3;)
              end
              local.get 0
              f64.const 0x1p+1023 (;=89884656743115800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
              f64.mul
              local.set 5
              br 4 (;@1;)
            end
            local.get 1
            local.get 0
            f64.const 0x1p+1023 (;=89884656743115800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
            f64.add
            f64.store offset=8
            local.get 0
            f64.const 0x1p+0 (;=1;)
            f64.add
            local.set 5
            local.get 1
            f64.load offset=8
            drop
            br 3 (;@1;)
          end
          local.get 3
          i32.const 1
          i32.xor
          local.get 3
          i32.sub
          local.set 4
        end
        local.get 0
        local.get 4
        f64.convert_i32_s
        local.tee 5
        f64.const -0x1.62e42feep-1 (;=-0.6931471803691238;)
        f64.mul
        f64.add
        local.tee 0
        local.get 5
        f64.const 0x1.a39ef35793c76p-33 (;=0.00000000019082149292705877;)
        f64.mul
        local.tee 6
        f64.sub
        local.set 5
      end
      local.get 0
      local.get 5
      local.get 5
      local.get 5
      local.get 5
      f64.mul
      local.tee 7
      local.get 7
      local.get 7
      local.get 7
      local.get 7
      f64.const 0x1.6376972bea4dp-25 (;=0.000000041381367970572385;)
      f64.mul
      f64.const -0x1.bbd41c5d26bf1p-20 (;=-0.0000016533902205465252;)
      f64.add
      f64.mul
      f64.const 0x1.1566aaf25de2cp-14 (;=0.00006613756321437934;)
      f64.add
      f64.mul
      f64.const -0x1.6c16c16bebd93p-9 (;=-0.0027777777777015593;)
      f64.add
      f64.mul
      f64.const 0x1.555555555553ep-3 (;=0.16666666666666602;)
      f64.add
      f64.mul
      f64.sub
      local.tee 7
      f64.mul
      f64.const 0x1p+1 (;=2;)
      local.get 7
      f64.sub
      f64.div
      local.get 6
      f64.sub
      f64.add
      f64.const 0x1p+0 (;=1;)
      f64.add
      local.set 5
      local.get 4
      i32.eqz
      br_if 0 (;@1;)
      local.get 5
      local.get 4
      call $mw_h1
      local.set 5
    end
    local.get 1
    i32.const 16
    i32.add
    global.set $mw_sp
    local.get 5
  )
  (func $mw_m_log (param f64) (result f64)
    (local i64 i32 i64 i32 f64 f64)
    block ;; label = @1
      block ;; label = @2
        block ;; label = @3
          block ;; label = @4
            local.get 0
            i64.reinterpret_f64
            local.tee 1
            i64.const 4503599627370496
            i64.lt_s
            br_if 0 (;@4;)
            local.get 1
            i64.const 9218868437227405311
            i64.gt_u
            br_if 3 (;@1;)
            i32.const -1023
            local.set 2
            block ;; label = @5
              local.get 1
              i64.const 32
              i64.shr_u
              local.tee 3
              i64.const 1072693248
              i64.eq
              br_if 0 (;@5;)
              local.get 3
              i32.wrap_i64
              local.set 4
              br 2 (;@3;)
            end
            i32.const 1072693248
            local.set 4
            local.get 1
            i32.wrap_i64
            br_if 1 (;@3;)
            f64.const 0x0p+0 (;=0;)
            return
          end
          block ;; label = @4
            local.get 0
            f64.const 0x0p+0 (;=0;)
            f64.ne
            br_if 0 (;@4;)
            f64.const -0x1p+0 (;=-1;)
            local.get 0
            local.get 0
            f64.mul
            f64.div
            return
          end
          local.get 1
          i64.const 0
          i64.lt_s
          br_if 1 (;@2;)
          local.get 0
          f64.const 0x1p+54 (;=18014398509481984;)
          f64.mul
          i64.reinterpret_f64
          local.tee 1
          i64.const 32
          i64.shr_u
          i32.wrap_i64
          local.set 4
          i32.const -1077
          local.set 2
        end
        local.get 2
        local.get 4
        i32.const 614242
        i32.add
        local.tee 4
        i32.const 20
        i32.shr_u
        i32.add
        f64.convert_i32_s
        local.tee 5
        f64.const 0x1.62e42feep-1 (;=0.6931471803691238;)
        f64.mul
        local.get 4
        i32.const 1048575
        i32.and
        i32.const 1072079006
        i32.add
        i64.extend_i32_u
        i64.const 32
        i64.shl
        local.get 1
        i64.const 4294967295
        i64.and
        i64.or
        f64.reinterpret_i64
        f64.const -0x1p+0 (;=-1;)
        f64.add
        local.tee 0
        local.get 5
        f64.const 0x1.a39ef35793c76p-33 (;=0.00000000019082149292705877;)
        f64.mul
        local.get 0
        local.get 0
        f64.const 0x1p+1 (;=2;)
        f64.add
        f64.div
        local.tee 5
        local.get 0
        local.get 0
        f64.const 0x1p-1 (;=0.5;)
        f64.mul
        f64.mul
        local.tee 6
        local.get 5
        local.get 5
        f64.mul
        local.tee 5
        local.get 5
        f64.mul
        local.tee 0
        local.get 0
        local.get 0
        f64.const 0x1.39a09d078c69fp-3 (;=0.15313837699209373;)
        f64.mul
        f64.const 0x1.c71c51d8e78afp-3 (;=0.22222198432149784;)
        f64.add
        f64.mul
        f64.const 0x1.999999997fa04p-2 (;=0.3999999999940942;)
        f64.add
        f64.mul
        local.get 5
        local.get 0
        local.get 0
        local.get 0
        f64.const 0x1.2f112df3e5244p-3 (;=0.14798198605116586;)
        f64.mul
        f64.const 0x1.7466496cb03dep-3 (;=0.1818357216161805;)
        f64.add
        f64.mul
        f64.const 0x1.2492494229359p-2 (;=0.2857142874366239;)
        f64.add
        f64.mul
        f64.const 0x1.5555555555593p-1 (;=0.6666666666666735;)
        f64.add
        f64.mul
        f64.add
        f64.add
        f64.mul
        f64.add
        local.get 6
        f64.sub
        f64.add
        f64.add
        return
      end
      local.get 0
      local.get 0
      f64.sub
      f64.const 0x0p+0 (;=0;)
      f64.div
      local.set 0
    end
    local.get 0
  )
  (func $mw_m_log10 (param f64) (result f64)
    (local i64 i32 i64 i32 f64 f64 f64 f64 f64 f64)
    block ;; label = @1
      block ;; label = @2
        block ;; label = @3
          block ;; label = @4
            local.get 0
            i64.reinterpret_f64
            local.tee 1
            i64.const 4503599627370496
            i64.lt_s
            br_if 0 (;@4;)
            local.get 1
            i64.const 9218868437227405311
            i64.gt_u
            br_if 3 (;@1;)
            i32.const -1023
            local.set 2
            block ;; label = @5
              local.get 1
              i64.const 32
              i64.shr_u
              local.tee 3
              i64.const 1072693248
              i64.eq
              br_if 0 (;@5;)
              local.get 3
              i32.wrap_i64
              local.set 4
              br 2 (;@3;)
            end
            i32.const 1072693248
            local.set 4
            local.get 1
            i32.wrap_i64
            br_if 1 (;@3;)
            f64.const 0x0p+0 (;=0;)
            return
          end
          block ;; label = @4
            local.get 0
            f64.const 0x0p+0 (;=0;)
            f64.ne
            br_if 0 (;@4;)
            f64.const -0x1p+0 (;=-1;)
            local.get 0
            local.get 0
            f64.mul
            f64.div
            return
          end
          local.get 1
          i64.const 0
          i64.lt_s
          br_if 1 (;@2;)
          local.get 0
          f64.const 0x1p+54 (;=18014398509481984;)
          f64.mul
          i64.reinterpret_f64
          local.tee 1
          i64.const 32
          i64.shr_u
          i32.wrap_i64
          local.set 4
          i32.const -1077
          local.set 2
        end
        local.get 2
        local.get 4
        i32.const 614242
        i32.add
        local.tee 4
        i32.const 20
        i32.shr_u
        i32.add
        f64.convert_i32_s
        local.tee 5
        f64.const 0x1.34413509f6p-2 (;=0.30102999566361177;)
        f64.mul
        local.tee 6
        local.get 4
        i32.const 1048575
        i32.and
        i32.const 1072079006
        i32.add
        i64.extend_i32_u
        i64.const 32
        i64.shl
        local.get 1
        i64.const 4294967295
        i64.and
        i64.or
        f64.reinterpret_i64
        f64.const -0x1p+0 (;=-1;)
        f64.add
        local.tee 0
        local.get 0
        local.get 0
        f64.const 0x1p-1 (;=0.5;)
        f64.mul
        f64.mul
        local.tee 7
        f64.sub
        i64.reinterpret_f64
        i64.const -4294967296
        i64.and
        f64.reinterpret_i64
        local.tee 8
        f64.const 0x1.bcb7b152p-2 (;=0.4342944818781689;)
        f64.mul
        local.tee 9
        f64.add
        local.tee 10
        local.get 9
        local.get 6
        local.get 10
        f64.sub
        f64.add
        local.get 0
        local.get 8
        f64.sub
        local.get 7
        f64.sub
        local.get 0
        local.get 0
        f64.const 0x1p+1 (;=2;)
        f64.add
        f64.div
        local.tee 0
        local.get 7
        local.get 0
        local.get 0
        f64.mul
        local.tee 6
        local.get 6
        f64.mul
        local.tee 0
        local.get 0
        local.get 0
        f64.const 0x1.39a09d078c69fp-3 (;=0.15313837699209373;)
        f64.mul
        f64.const 0x1.c71c51d8e78afp-3 (;=0.22222198432149784;)
        f64.add
        f64.mul
        f64.const 0x1.999999997fa04p-2 (;=0.3999999999940942;)
        f64.add
        f64.mul
        local.get 6
        local.get 0
        local.get 0
        local.get 0
        f64.const 0x1.2f112df3e5244p-3 (;=0.14798198605116586;)
        f64.mul
        f64.const 0x1.7466496cb03dep-3 (;=0.1818357216161805;)
        f64.add
        f64.mul
        f64.const 0x1.2492494229359p-2 (;=0.2857142874366239;)
        f64.add
        f64.mul
        f64.const 0x1.5555555555593p-1 (;=0.6666666666666735;)
        f64.add
        f64.mul
        f64.add
        f64.add
        f64.mul
        f64.add
        local.tee 0
        f64.const 0x1.bcb7b152p-2 (;=0.4342944818781689;)
        f64.mul
        local.get 5
        f64.const 0x1.9fef311f12b36p-42 (;=0.0000000000003694239077158931;)
        f64.mul
        local.get 0
        local.get 8
        f64.add
        f64.const 0x1.b9438ca9aadd5p-36 (;=0.000000000025082946711645275;)
        f64.mul
        f64.add
        f64.add
        f64.add
        f64.add
        return
      end
      local.get 0
      local.get 0
      f64.sub
      f64.const 0x0p+0 (;=0;)
      f64.div
      local.set 0
    end
    local.get 0
  )
  (func $mw_m_log2 (param f64) (result f64)
    (local i64 i32 i64 i32 f64 f64 f64 f64 f64)
    block ;; label = @1
      block ;; label = @2
        block ;; label = @3
          block ;; label = @4
            local.get 0
            i64.reinterpret_f64
            local.tee 1
            i64.const 4503599627370496
            i64.lt_s
            br_if 0 (;@4;)
            local.get 1
            i64.const 9218868437227405311
            i64.gt_u
            br_if 3 (;@1;)
            i32.const -1023
            local.set 2
            block ;; label = @5
              local.get 1
              i64.const 32
              i64.shr_u
              local.tee 3
              i64.const 1072693248
              i64.eq
              br_if 0 (;@5;)
              local.get 3
              i32.wrap_i64
              local.set 4
              br 2 (;@3;)
            end
            i32.const 1072693248
            local.set 4
            local.get 1
            i32.wrap_i64
            br_if 1 (;@3;)
            f64.const 0x0p+0 (;=0;)
            return
          end
          block ;; label = @4
            local.get 0
            f64.const 0x0p+0 (;=0;)
            f64.ne
            br_if 0 (;@4;)
            f64.const -0x1p+0 (;=-1;)
            local.get 0
            local.get 0
            f64.mul
            f64.div
            return
          end
          local.get 1
          i64.const 0
          i64.lt_s
          br_if 1 (;@2;)
          local.get 0
          f64.const 0x1p+54 (;=18014398509481984;)
          f64.mul
          i64.reinterpret_f64
          local.tee 1
          i64.const 32
          i64.shr_u
          i32.wrap_i64
          local.set 4
          i32.const -1077
          local.set 2
        end
        local.get 4
        i32.const 614242
        i32.add
        local.tee 4
        i32.const 1048575
        i32.and
        i32.const 1072079006
        i32.add
        i64.extend_i32_u
        i64.const 32
        i64.shl
        local.get 1
        i64.const 4294967295
        i64.and
        i64.or
        f64.reinterpret_i64
        f64.const -0x1p+0 (;=-1;)
        f64.add
        local.tee 0
        local.get 0
        local.get 0
        f64.const 0x1p-1 (;=0.5;)
        f64.mul
        f64.mul
        local.tee 5
        f64.sub
        i64.reinterpret_f64
        i64.const -4294967296
        i64.and
        f64.reinterpret_i64
        local.tee 6
        f64.const 0x1.71547652p+0 (;=1.4426950407214463;)
        f64.mul
        local.tee 7
        local.get 2
        local.get 4
        i32.const 20
        i32.shr_u
        i32.add
        f64.convert_i32_s
        local.tee 8
        f64.add
        local.tee 9
        local.get 7
        local.get 8
        local.get 9
        f64.sub
        f64.add
        local.get 0
        local.get 6
        f64.sub
        local.get 5
        f64.sub
        local.get 0
        local.get 0
        f64.const 0x1p+1 (;=2;)
        f64.add
        f64.div
        local.tee 0
        local.get 5
        local.get 0
        local.get 0
        f64.mul
        local.tee 7
        local.get 7
        f64.mul
        local.tee 0
        local.get 0
        local.get 0
        f64.const 0x1.39a09d078c69fp-3 (;=0.15313837699209373;)
        f64.mul
        f64.const 0x1.c71c51d8e78afp-3 (;=0.22222198432149784;)
        f64.add
        f64.mul
        f64.const 0x1.999999997fa04p-2 (;=0.3999999999940942;)
        f64.add
        f64.mul
        local.get 7
        local.get 0
        local.get 0
        local.get 0
        f64.const 0x1.2f112df3e5244p-3 (;=0.14798198605116586;)
        f64.mul
        f64.const 0x1.7466496cb03dep-3 (;=0.1818357216161805;)
        f64.add
        f64.mul
        f64.const 0x1.2492494229359p-2 (;=0.2857142874366239;)
        f64.add
        f64.mul
        f64.const 0x1.5555555555593p-1 (;=0.6666666666666735;)
        f64.add
        f64.mul
        f64.add
        f64.add
        f64.mul
        f64.add
        local.tee 0
        f64.const 0x1.71547652p+0 (;=1.4426950407214463;)
        f64.mul
        local.get 0
        local.get 6
        f64.add
        f64.const 0x1.705fc2eefa2p-33 (;=0.00000000016751713164886512;)
        f64.mul
        f64.add
        f64.add
        f64.add
        return
      end
      local.get 0
      local.get 0
      f64.sub
      f64.const 0x0p+0 (;=0;)
      f64.div
      local.set 0
    end
    local.get 0
  )
  (func $mw_m_pow (param f64 f64) (result f64)
    (local i32 f64 i64 i32 i32 i32 i64 i32 i64 i32 i32 i32 i32 i32 i64 f64 f64 f64 f64)
    global.get $mw_sp
    i32.const 48
    i32.sub
    local.tee 2
    global.set $mw_sp
    f64.const 0x1p+0 (;=1;)
    local.set 3
    block ;; label = @1
      local.get 1
      i64.reinterpret_f64
      local.tee 4
      i64.const 32
      i64.shr_u
      i32.wrap_i64
      local.tee 5
      i32.const 2147483647
      i32.and
      local.tee 6
      local.get 4
      i32.wrap_i64
      local.tee 7
      i32.or
      i32.eqz
      br_if 0 (;@1;)
      local.get 0
      i64.reinterpret_f64
      local.tee 8
      i32.wrap_i64
      local.set 9
      block ;; label = @2
        local.get 8
        i64.const 32
        i64.shr_u
        local.tee 10
        i64.const 1072693248
        i64.ne
        br_if 0 (;@2;)
        local.get 9
        i32.eqz
        br_if 1 (;@1;)
      end
      block ;; label = @2
        block ;; label = @3
          block ;; label = @4
            block ;; label = @5
              block ;; label = @6
                block ;; label = @7
                  block ;; label = @8
                    local.get 10
                    i32.wrap_i64
                    local.tee 11
                    i32.const 2147483647
                    i32.and
                    local.tee 12
                    i32.const 2146435072
                    i32.gt_u
                    br_if 0 (;@8;)
                    block ;; label = @9
                      block ;; label = @10
                        local.get 12
                        i32.const 2146435072
                        i32.ne
                        br_if 0 (;@10;)
                        local.get 9
                        br_if 2 (;@8;)
                        local.get 6
                        i32.const 2146435072
                        i32.gt_u
                        br_if 2 (;@8;)
                        br 1 (;@9;)
                      end
                      local.get 6
                      i32.const 2146435073
                      i32.ge_u
                      br_if 1 (;@8;)
                    end
                    block ;; label = @9
                      local.get 7
                      i32.eqz
                      br_if 0 (;@9;)
                      local.get 6
                      i32.const 2146435072
                      i32.eq
                      br_if 1 (;@8;)
                    end
                    local.get 8
                    i64.const 0
                    i64.lt_s
                    br_if 1 (;@7;)
                    br 2 (;@6;)
                  end
                  local.get 0
                  local.get 1
                  f64.add
                  local.set 3
                  br 6 (;@1;)
                end
                i32.const 2
                local.set 13
                local.get 6
                i32.const 1128267775
                i32.gt_u
                br_if 1 (;@5;)
                local.get 6
                i32.const 1072693248
                i32.lt_u
                br_if 0 (;@6;)
                local.get 6
                i32.const 20
                i32.shr_u
                local.set 14
                block ;; label = @7
                  local.get 6
                  i32.const 1094713343
                  i32.gt_u
                  br_if 0 (;@7;)
                  i32.const 0
                  local.set 13
                  local.get 7
                  br_if 4 (;@3;)
                  i32.const 0
                  local.set 13
                  local.get 6
                  i32.const 1043
                  local.get 14
                  i32.sub
                  local.tee 7
                  i32.shr_u
                  local.tee 14
                  local.get 7
                  i32.shl
                  local.get 6
                  i32.ne
                  br_if 3 (;@4;)
                  i32.const 2
                  local.get 14
                  i32.const 1
                  i32.and
                  i32.sub
                  local.set 13
                  br 3 (;@4;)
                end
                i32.const 0
                local.set 13
                local.get 7
                i32.const 1075
                local.get 14
                i32.sub
                local.tee 14
                i32.shr_u
                local.tee 15
                local.get 14
                i32.shl
                local.get 7
                i32.ne
                br_if 1 (;@5;)
                i32.const 2
                local.get 15
                i32.const 1
                i32.and
                i32.sub
                local.set 13
                br 1 (;@5;)
              end
              i32.const 0
              local.set 13
            end
            local.get 7
            br_if 1 (;@3;)
          end
          block ;; label = @4
            block ;; label = @5
              block ;; label = @6
                block ;; label = @7
                  block ;; label = @8
                    block ;; label = @9
                      local.get 6
                      i32.const 1072693248
                      i32.eq
                      br_if 0 (;@9;)
                      local.get 6
                      i32.const 2146435072
                      i32.ne
                      br_if 1 (;@8;)
                      local.get 12
                      i32.const -1072693248
                      i32.add
                      local.get 9
                      i32.or
                      i32.eqz
                      br_if 8 (;@1;)
                      local.get 12
                      i32.const 1072693247
                      i32.gt_u
                      br_if 5 (;@4;)
                      f64.const 0x0p+0 (;=0;)
                      local.get 1
                      f64.neg
                      local.get 4
                      i64.const -1
                      i64.gt_s
                      select
                      local.set 3
                      br 8 (;@1;)
                    end
                    local.get 4
                    i64.const -1
                    i64.le_s
                    br_if 1 (;@7;)
                    br 6 (;@2;)
                  end
                  local.get 5
                  i32.const 1071644672
                  i32.eq
                  br_if 2 (;@5;)
                  local.get 5
                  i32.const 1073741824
                  i32.eq
                  br_if 1 (;@6;)
                  br 4 (;@3;)
                end
                f64.const 0x1p+0 (;=1;)
                local.get 0
                f64.div
                local.set 3
                br 5 (;@1;)
              end
              local.get 0
              local.get 0
              f64.mul
              local.set 3
              br 4 (;@1;)
            end
            local.get 8
            i64.const 0
            i64.lt_s
            br_if 1 (;@3;)
            block ;; label = @5
              local.get 8
              i64.const 52
              i64.shr_u
              i32.wrap_i64
              local.tee 9
              i32.const -2047
              i32.add
              i32.const -2047
              i32.gt_u
              br_if 0 (;@5;)
              local.get 0
              f64.const 0x0p+0 (;=0;)
              f64.eq
              br_if 3 (;@2;)
              local.get 8
              i64.const 9218868437227405312
              i64.eq
              br_if 3 (;@2;)
              f64.const nan (;=NaN;)
              local.set 3
              local.get 8
              i64.const 9218868437227405312
              i64.gt_u
              br_if 4 (;@1;)
              local.get 0
              f64.const 0x1p+52 (;=4503599627370496;)
              f64.mul
              i64.reinterpret_f64
              local.tee 8
              i64.const 52
              i64.shr_u
              i32.wrap_i64
              i32.const 2047
              i32.and
              i32.const -52
              i32.add
              local.set 9
            end
            i32.const 2
            local.set 6
            local.get 8
            i64.const 11
            i64.shl
            i64.const -9223372036854775808
            i64.or
            local.get 9
            i32.const 1
            i32.and
            i64.extend_i32_u
            i64.shr_u
            local.tee 16
            local.set 10
            local.get 8
            i64.const 46
            i64.shr_u
            i32.wrap_i64
            i32.const 127
            i32.and
            i32.const 1
            i32.shl
            i32.load16_u offset=16448
            i32.const 16
            i32.shl
            local.get 16
            i64.const 32
            i64.shr_u
            i32.wrap_i64
            local.tee 7
            i32.const 0
            call $mw_h0
            local.get 7
            i32.const 2
            call $mw_h0
            i64.extend_i32_u
            i64.const 32
            i64.shl
            local.tee 8
            local.set 4
            block ;; label = @5
              loop ;; label = @6
                local.get 6
                i32.eqz
                br_if 1 (;@5;)
                local.get 2
                i32.const 32
                i32.add
                local.get 8
                i64.const 0
                local.get 10
                i64.const 0
                call $mw_h7
                local.get 2
                i32.const 16
                i32.add
                local.get 2
                i64.load offset=40
                local.tee 10
                i64.const 0
                local.get 4
                i64.const 0
                call $mw_h7
                local.get 2
                i64.const -4611686018427387904
                local.get 2
                i64.load offset=24
                i64.sub
                local.tee 8
                i64.const 0
                local.get 4
                i64.const 0
                call $mw_h7
                local.get 6
                i32.const -1
                i32.add
                local.set 6
                local.get 2
                i64.load offset=8
                i64.const 1
                i64.shl
                local.set 4
                br 0 (;@6;)
              end
            end
            local.get 10
            i64.const 9
            i64.shr_u
            local.tee 4
            local.get 4
            i64.mul
            local.get 16
            i64.const 42
            i64.shl
            i64.sub
            local.get 4
            i64.add
            local.tee 8
            i64.const 63
            i64.shr_u
            local.get 4
            i64.add
            i64.const 4503599627370495
            i64.and
            local.get 9
            i32.const 1023
            i32.add
            i32.const 1
            i32.shr_u
            i64.extend_i32_u
            i64.const 52
            i64.shl
            i64.or
            local.tee 4
            f64.reinterpret_i64
            i64.const 0
            i64.const 4503599627370496
            local.get 8
            local.get 4
            i64.add
            i64.const 1
            i64.add
            local.tee 4
            i64.eqz
            select
            local.get 4
            local.get 8
            i64.xor
            i64.const -9223372036854775808
            i64.and
            i64.or
            f64.reinterpret_i64
            f64.add
            local.set 3
            br 3 (;@1;)
          end
          local.get 1
          f64.const 0x0p+0 (;=0;)
          local.get 4
          i64.const -1
          i64.gt_s
          select
          local.set 3
          br 2 (;@1;)
        end
        local.get 0
        f64.abs
        local.set 3
        block ;; label = @3
          block ;; label = @4
            block ;; label = @5
              block ;; label = @6
                block ;; label = @7
                  local.get 9
                  br_if 0 (;@7;)
                  local.get 11
                  i32.const -2147483648
                  i32.eq
                  br_if 1 (;@6;)
                  local.get 11
                  i32.const -1074790400
                  i32.eq
                  br_if 1 (;@6;)
                  local.get 11
                  i32.const -1048576
                  i32.eq
                  br_if 1 (;@6;)
                  local.get 11
                  i32.eqz
                  br_if 1 (;@6;)
                  local.get 11
                  i32.const 1072693248
                  i32.eq
                  br_if 1 (;@6;)
                  local.get 11
                  i32.const 2146435072
                  i32.eq
                  br_if 1 (;@6;)
                end
                f64.const 0x1p+0 (;=1;)
                local.set 17
                local.get 8
                i64.const 0
                i64.ge_s
                br_if 3 (;@3;)
                local.get 13
                br_table 1 (;@5;) 2 (;@4;) 3 (;@3;)
              end
              f64.const 0x1p+0 (;=1;)
              local.get 3
              f64.div
              local.get 3
              local.get 4
              i64.const 0
              i64.lt_s
              select
              local.set 3
              local.get 8
              i64.const -1
              i64.gt_s
              br_if 4 (;@1;)
              block ;; label = @6
                local.get 13
                local.get 12
                i32.const -1072693248
                i32.add
                i32.or
                br_if 0 (;@6;)
                local.get 3
                local.get 3
                f64.sub
                local.tee 3
                local.get 3
                f64.div
                local.set 3
                br 5 (;@1;)
              end
              local.get 3
              f64.neg
              local.get 3
              local.get 13
              i32.const 1
              i32.eq
              select
              local.set 3
              br 4 (;@1;)
            end
            local.get 0
            local.get 0
            f64.sub
            local.tee 3
            local.get 3
            f64.div
            local.set 3
            br 3 (;@1;)
          end
          f64.const -0x1p+0 (;=-1;)
          local.set 17
        end
        block ;; label = @3
          block ;; label = @4
            local.get 6
            i32.const 1105199104
            i32.gt_u
            br_if 0 (;@4;)
            local.get 3
            f64.const 0x1p+53 (;=9007199254740992;)
            f64.mul
            local.tee 0
            local.get 3
            local.get 12
            i32.const 1048576
            i32.lt_u
            local.tee 9
            select
            local.set 18
            local.get 0
            i64.reinterpret_f64
            i64.const 32
            i64.shr_u
            i32.wrap_i64
            local.get 12
            local.get 9
            select
            local.tee 5
            i32.const 1048575
            i32.and
            local.tee 7
            i32.const 1072693248
            i32.or
            local.set 6
            i32.const -1076
            i32.const -1023
            local.get 9
            select
            local.get 5
            i32.const 20
            i32.shr_s
            i32.add
            local.set 5
            i32.const 0
            local.set 9
            block ;; label = @5
              local.get 7
              i32.const 235663
              i32.lt_u
              br_if 0 (;@5;)
              block ;; label = @6
                local.get 7
                i32.const 767610
                i32.ge_u
                br_if 0 (;@6;)
                i32.const 1
                local.set 9
                br 1 (;@5;)
              end
              local.get 7
              i32.const 1071644672
              i32.or
              local.set 6
              local.get 5
              i32.const 1
              i32.add
              local.set 5
            end
            local.get 9
            i32.const 3
            i32.shl
            local.tee 7
            f64.load offset=16416
            f64.const 0x1p+0 (;=1;)
            local.get 7
            f64.load offset=16400
            local.tee 3
            local.get 6
            i64.extend_i32_u
            i64.const 32
            i64.shl
            local.get 18
            i64.reinterpret_f64
            i64.const 4294967295
            i64.and
            i64.or
            f64.reinterpret_i64
            local.tee 19
            f64.add
            f64.div
            local.tee 0
            local.get 19
            local.get 3
            f64.sub
            local.tee 18
            local.get 9
            i32.const 18
            i32.shl
            local.get 6
            i32.const 1
            i32.shr_u
            i32.add
            i32.const 537395200
            i32.add
            i64.extend_i32_u
            i64.const 32
            i64.shl
            f64.reinterpret_i64
            local.tee 20
            local.get 18
            local.get 0
            f64.mul
            local.tee 18
            i64.reinterpret_f64
            i64.const -4294967296
            i64.and
            f64.reinterpret_i64
            local.tee 0
            f64.mul
            f64.sub
            local.get 3
            local.get 20
            f64.sub
            local.get 19
            f64.add
            local.get 0
            f64.mul
            f64.sub
            f64.mul
            local.tee 3
            local.get 0
            local.get 0
            f64.mul
            local.tee 19
            f64.const 0x1.8p+1 (;=3;)
            f64.add
            local.get 3
            local.get 18
            local.get 0
            f64.add
            f64.mul
            local.get 18
            local.get 18
            f64.mul
            local.tee 3
            local.get 3
            f64.mul
            local.get 3
            local.get 3
            local.get 3
            local.get 3
            local.get 3
            f64.const 0x1.a7e284a454eefp-3 (;=0.20697501780033842;)
            f64.mul
            f64.const 0x1.d864a93c9db65p-3 (;=0.23066074577556175;)
            f64.add
            f64.mul
            f64.const 0x1.17460a91d4101p-2 (;=0.272728123808534;)
            f64.add
            f64.mul
            f64.const 0x1.55555518f264dp-2 (;=0.33333332981837743;)
            f64.add
            f64.mul
            f64.const 0x1.b6db6db6fabffp-2 (;=0.4285714285785502;)
            f64.add
            f64.mul
            f64.const 0x1.3333333333303p-1 (;=0.5999999999999946;)
            f64.add
            f64.mul
            f64.add
            local.tee 20
            f64.add
            i64.reinterpret_f64
            i64.const -4294967296
            i64.and
            f64.reinterpret_i64
            local.tee 3
            f64.mul
            local.get 18
            local.get 20
            local.get 3
            f64.const -0x1.8p+1 (;=-3;)
            f64.add
            local.get 19
            f64.sub
            f64.sub
            f64.mul
            f64.add
            local.tee 18
            local.get 18
            local.get 0
            local.get 3
            f64.mul
            local.tee 0
            f64.add
            i64.reinterpret_f64
            i64.const -4294967296
            i64.and
            f64.reinterpret_i64
            local.tee 3
            local.get 0
            f64.sub
            f64.sub
            f64.const 0x1.ec709dc3a03fdp-1 (;=0.9617966939259756;)
            f64.mul
            local.get 3
            f64.const -0x1.e2fe0145b01f5p-28 (;=-0.000000007028461650952758;)
            f64.mul
            f64.add
            f64.add
            local.tee 0
            local.get 7
            f64.load offset=16432
            local.tee 18
            local.get 0
            local.get 3
            f64.const 0x1.ec709ep-1 (;=0.9617967009544373;)
            f64.mul
            local.tee 19
            f64.add
            f64.add
            local.get 5
            f64.convert_i32_s
            local.tee 0
            f64.add
            i64.reinterpret_f64
            i64.const -4294967296
            i64.and
            f64.reinterpret_i64
            local.tee 3
            local.get 0
            f64.sub
            local.get 18
            f64.sub
            local.get 19
            f64.sub
            f64.sub
            local.set 18
            br 1 (;@3;)
          end
          block ;; label = @4
            block ;; label = @5
              block ;; label = @6
                local.get 6
                i32.const 1139802112
                i32.gt_u
                br_if 0 (;@6;)
                local.get 12
                i32.const 1072693247
                i32.lt_u
                br_if 2 (;@4;)
                local.get 12
                i32.const 1072693248
                i32.gt_u
                br_if 1 (;@5;)
                local.get 3
                f64.const -0x1p+0 (;=-1;)
                f64.add
                local.tee 3
                f64.const 0x1.4ae0bf85ddf44p-26 (;=0.000000019259629911266175;)
                f64.mul
                local.get 3
                local.get 3
                f64.mul
                f64.const 0x1p-1 (;=0.5;)
                local.get 3
                local.get 3
                f64.const -0x1p-2 (;=-0.25;)
                f64.mul
                f64.const 0x1.5555555555555p-2 (;=0.3333333333333333;)
                f64.add
                f64.mul
                f64.sub
                f64.mul
                f64.const -0x1.71547652b82fep+0 (;=-1.4426950408889634;)
                f64.mul
                f64.add
                local.tee 0
                local.get 0
                local.get 3
                f64.const 0x1.715476p+0 (;=1.4426950216293335;)
                f64.mul
                local.tee 18
                f64.add
                i64.reinterpret_f64
                i64.const -4294967296
                i64.and
                f64.reinterpret_i64
                local.tee 3
                local.get 18
                f64.sub
                f64.sub
                local.set 18
                br 3 (;@3;)
              end
              block ;; label = @6
                local.get 12
                i32.const 1072693247
                i32.gt_u
                br_if 0 (;@6;)
                f64.const inf (;=inf;)
                f64.const 0x0p+0 (;=0;)
                local.get 4
                i64.const 0
                i64.lt_s
                select
                local.set 3
                br 5 (;@1;)
              end
              f64.const inf (;=inf;)
              f64.const 0x0p+0 (;=0;)
              local.get 5
              i32.const 0
              i32.gt_s
              select
              local.set 3
              br 4 (;@1;)
            end
            block ;; label = @5
              local.get 5
              i32.const 0
              i32.gt_s
              br_if 0 (;@5;)
              local.get 17
              f64.const 0x1.56e1fc2f8f359p-997 (;=0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001;)
              f64.mul
              f64.const 0x1.56e1fc2f8f359p-997 (;=0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001;)
              f64.mul
              local.set 3
              br 4 (;@1;)
            end
            local.get 17
            f64.const 0x1.7e43c8800759cp+996 (;=1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
            f64.mul
            f64.const 0x1.7e43c8800759cp+996 (;=1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
            f64.mul
            local.set 3
            br 3 (;@1;)
          end
          block ;; label = @4
            local.get 4
            i64.const 0
            i64.lt_s
            br_if 0 (;@4;)
            local.get 17
            f64.const 0x1.56e1fc2f8f359p-997 (;=0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001;)
            f64.mul
            f64.const 0x1.56e1fc2f8f359p-997 (;=0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001;)
            f64.mul
            local.set 3
            br 3 (;@1;)
          end
          local.get 17
          f64.const 0x1.7e43c8800759cp+996 (;=1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
          f64.mul
          f64.const 0x1.7e43c8800759cp+996 (;=1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
          f64.mul
          local.set 3
          br 2 (;@1;)
        end
        local.get 3
        local.get 4
        i64.const -4294967296
        i64.and
        f64.reinterpret_i64
        local.tee 19
        f64.mul
        local.tee 0
        local.get 1
        local.get 19
        f64.sub
        local.get 3
        f64.mul
        local.get 1
        local.get 18
        f64.mul
        f64.add
        local.tee 3
        f64.add
        local.tee 1
        i64.reinterpret_f64
        local.tee 4
        i32.wrap_i64
        local.set 9
        block ;; label = @3
          block ;; label = @4
            block ;; label = @5
              local.get 4
              i64.const 32
              i64.shr_u
              i32.wrap_i64
              local.tee 6
              i32.const 1083179007
              i32.gt_s
              br_if 0 (;@5;)
              local.get 6
              i32.const 2147482624
              i32.and
              i32.const 1083231231
              i32.le_u
              br_if 2 (;@3;)
              local.get 6
              i32.const 1064252416
              i32.add
              local.get 9
              i32.or
              br_if 1 (;@4;)
              local.get 3
              local.get 1
              local.get 0
              f64.sub
              f64.le
              i32.eqz
              br_if 2 (;@3;)
              local.get 17
              f64.const 0x1.56e1fc2f8f359p-997 (;=0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001;)
              f64.mul
              f64.const 0x1.56e1fc2f8f359p-997 (;=0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001;)
              f64.mul
              local.set 3
              br 4 (;@1;)
            end
            block ;; label = @5
              local.get 6
              i32.const -1083179008
              i32.add
              local.get 9
              i32.or
              i32.eqz
              br_if 0 (;@5;)
              local.get 17
              f64.const 0x1.7e43c8800759cp+996 (;=1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
              f64.mul
              f64.const 0x1.7e43c8800759cp+996 (;=1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
              f64.mul
              local.set 3
              br 4 (;@1;)
            end
            local.get 3
            f64.const 0x1.71547652b82fep-54 (;=0.00000000000000008008566259537294;)
            f64.add
            local.get 1
            local.get 0
            f64.sub
            f64.gt
            i32.eqz
            br_if 1 (;@3;)
            local.get 17
            f64.const 0x1.7e43c8800759cp+996 (;=1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
            f64.mul
            f64.const 0x1.7e43c8800759cp+996 (;=1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;)
            f64.mul
            local.set 3
            br 3 (;@1;)
          end
          local.get 17
          f64.const 0x1.56e1fc2f8f359p-997 (;=0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001;)
          f64.mul
          f64.const 0x1.56e1fc2f8f359p-997 (;=0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001;)
          f64.mul
          local.set 3
          br 2 (;@1;)
        end
        i32.const 0
        local.set 9
        block ;; label = @3
          local.get 6
          i32.const 2147483647
          i32.and
          i32.const 1071644672
          i32.le_u
          br_if 0 (;@3;)
          i32.const 0
          i32.const 1048576
          local.get 6
          i32.const 20
          i32.shr_u
          i32.const 2
          i32.add
          i32.shr_u
          local.get 6
          i32.add
          local.tee 6
          i32.const 1048575
          i32.and
          i32.const 1048576
          i32.or
          i32.const 19
          local.get 6
          i32.const 20
          i32.shr_u
          local.tee 7
          i32.sub
          i32.shr_u
          local.tee 9
          i32.sub
          local.get 9
          local.get 4
          i64.const 0
          i64.lt_s
          select
          local.set 9
          local.get 3
          local.get 0
          i32.const -1048576
          local.get 7
          i32.const 1
          i32.add
          i32.shr_s
          local.get 6
          i32.and
          i64.extend_i32_u
          i64.const 32
          i64.shl
          f64.reinterpret_i64
          f64.sub
          local.tee 0
          f64.add
          i64.reinterpret_f64
          local.set 4
        end
        block ;; label = @3
          block ;; label = @4
            local.get 9
            i32.const 20
            i32.shl
            local.get 4
            i64.const -4294967296
            i64.and
            f64.reinterpret_i64
            local.tee 1
            f64.const 0x1.62e43p-1 (;=0.6931471824645996;)
            f64.mul
            local.tee 18
            local.get 3
            local.get 1
            local.get 0
            f64.sub
            f64.sub
            f64.const 0x1.62e42fefa39efp-1 (;=0.6931471805599453;)
            f64.mul
            local.get 1
            f64.const -0x1.05c610ca86c39p-29 (;=-0.000000001904654299957768;)
            f64.mul
            f64.add
            local.tee 0
            f64.add
            local.tee 3
            local.get 3
            local.get 3
            local.get 3
            local.get 3
            f64.mul
            local.tee 1
            local.get 1
            local.get 1
            local.get 1
            local.get 1
            f64.const 0x1.6376972bea4dp-25 (;=0.000000041381367970572385;)
            f64.mul
            f64.const -0x1.bbd41c5d26bf1p-20 (;=-0.0000016533902205465252;)
            f64.add
            f64.mul
            f64.const 0x1.1566aaf25de2cp-14 (;=0.00006613756321437934;)
            f64.add
            f64.mul
            f64.const -0x1.6c16c16bebd93p-9 (;=-0.0027777777777015593;)
            f64.add
            f64.mul
            f64.const 0x1.555555555553ep-3 (;=0.16666666666666602;)
            f64.add
            f64.mul
            f64.sub
            local.tee 1
            f64.mul
            local.get 1
            f64.const -0x1p+1 (;=-2;)
            f64.add
            f64.div
            local.get 0
            local.get 3
            local.get 18
            f64.sub
            f64.sub
            local.tee 1
            local.get 3
            local.get 1
            f64.mul
            f64.add
            f64.sub
            f64.sub
            f64.const 0x1p+0 (;=1;)
            f64.add
            local.tee 3
            i64.reinterpret_f64
            local.tee 4
            i64.const 32
            i64.shr_u
            i32.wrap_i64
            i32.add
            local.tee 6
            i32.const 1048576
            i32.lt_s
            br_if 0 (;@4;)
            local.get 6
            i64.extend_i32_u
            i64.const 32
            i64.shl
            local.get 4
            i64.const 4294967295
            i64.and
            i64.or
            f64.reinterpret_i64
            local.set 3
            br 1 (;@3;)
          end
          local.get 3
          local.get 9
          call $mw_h1
          local.set 3
        end
        local.get 17
        local.get 3
        f64.mul
        local.set 3
        br 1 (;@1;)
      end
      local.get 0
      local.set 3
    end
    local.get 2
    i32.const 48
    i32.add
    global.set $mw_sp
    local.get 3
  )
  (func $mw_h7 (param i32 i64 i64 i64 i64)
    (local i64 i64 i64 i64 i64 i64)
    local.get 0
    local.get 3
    i64.const 4294967295
    i64.and
    local.tee 5
    local.get 1
    i64.const 4294967295
    i64.and
    local.tee 6
    i64.mul
    local.tee 7
    local.get 3
    i64.const 32
    i64.shr_u
    local.tee 8
    local.get 6
    i64.mul
    local.tee 6
    local.get 5
    local.get 1
    i64.const 32
    i64.shr_u
    local.tee 9
    i64.mul
    i64.add
    local.tee 5
    i64.const 32
    i64.shl
    i64.add
    local.tee 10
    i64.store
    local.get 0
    local.get 8
    local.get 9
    i64.mul
    local.get 5
    local.get 6
    i64.lt_u
    i64.extend_i32_u
    i64.const 32
    i64.shl
    local.get 5
    i64.const 32
    i64.shr_u
    i64.or
    i64.add
    local.get 10
    local.get 7
    i64.lt_u
    i64.extend_i32_u
    i64.add
    local.get 4
    local.get 1
    i64.mul
    local.get 3
    local.get 2
    i64.mul
    i64.add
    i64.add
    i64.store offset=8
  )"#;
